### ISSUE TITLE
Adicionar Suporte para Assumir Roles (Funções) da AWS

### ISSUE THREAD

**Issue by edopneto** [pyinsole/pyinsole#6]
### Descrição

**Solicitação de Funcionalidade**: Adicionar suporte para assumir roles (funções) do IAM da AWS no projeto.

Atualmente, o projeto requer credenciais explícitas da AWS (como `AWS_ACCESS_KEY_ID` e `AWS_SECRET_ACCESS_KEY`) para acessar recursos da AWS. Ao adicionar suporte para assumir roles, o projeto poderá aproveitar as credenciais temporárias e permissões dinâmicas da AWS, aumentando a segurança e flexibilidade.

### Justificativa

Suportar roles assumidos da AWS oferece várias vantagens:

1. **Aumento de Segurança**: Em vez de depender de chaves de acesso de longo prazo, roles assumidas utilizam credenciais temporárias, reduzindo o risco de vazamento de credenciais.
2. **Controle de Acesso Flexível**: Roles assumidas permitem que os usuários concedam permissões de forma dinâmica, facilitando o gerenciamento de acesso granular a recursos específicos da AWS.
3. **Suporte Multi-Conta**: Roles assumidas simplificam o acesso a recursos em várias contas da AWS, especialmente em ambientes com permissões diferenciadas ou variados contextos de ambiente (ex.: produção e desenvolvimento).

### Proposta de Implementação

1. **Permitir Configuração de ARN da Role**: Adicionar uma opção para configurar um ARN de role da AWS que o projeto deve assumir.
2. **Gerenciamento de Sessão**: Utilizar o AWS STS (Serviço de Token de Segurança) para solicitar credenciais temporárias ao assumir a role.
3. **Fallback para Credenciais Padrão**: Caso nenhuma role seja especificada, o projeto deve utilizar as credenciais da AWS já existentes, garantindo compatibilidade retroativa.

### Exemplo de Uso

1. **Variáveis de Ambiente**:
   - `AWS_ROLE_ARN`: Especifica o ARN da role a ser assumida.
   - `AWS_ROLE_SESSION_NAME`: Define um nome de sessão opcional para fins de rastreamento.

2. **Exemplo de Código**:
   ```python
   import boto3

   def get_session():
       role_arn = os.getenv("AWS_ROLE_ARN")
       session_name = os.getenv("AWS_ROLE_SESSION_NAME", "default-session")
       
       if role_arn:
           sts_client = boto3.client("sts")
           assumed_role = sts_client.assume_role(RoleArn=role_arn, RoleSessionName=session_name)
           credentials = assumed_role["Credentials"]
           return boto3.Session(
               aws_access_key_id=credentials["AccessKeyId"],
               aws_secret_access_key=credentials["SecretAccessKey"],
               aws_session_token=credentials["SessionToken"]
           )
       else:
           return boto3.Session()

   # Uso
   session = get_session()
   ```

### Contexto Adicional

Implementar essa funcionalidade tornaria o projeto mais adaptável para uso em diversos ambientes AWS, como pipelines de CI/CD automatizados, configurações multi-conta e ambientes com requisitos de segurança rígidos.

**Feedback Bem-Vindo**: Gostaria de receber feedback sobre esta proposta, especialmente em relação a abordagens de implementação alternativas ou casos de uso adicionais que devem ser considerados.

**Comment by hartungstenio** [comment]
O projeto já suporta assumir funções configuradas via envvar. Só não passar nenhum parâmetro de autenticação (nenhum `aws_access_key_id`) que o que está configurado na máquina como envvars será usado.

Não acho que deveríamos fazer essa requisição para o STS dentro do ´pyinsole´. No fim, precisamos de um `aws_access_key_id` e `aws_secret_access_key`, e nada impede de o usuário solicitar isso por fora.

Particularmente, nem receberia esses parâmetros, e já receberia ou a sessão ou o cliente diretamente. Cada um tem suas vantagens e desvantagens.

## Recebendo a sessão
Receber a sessão é mais simples. O usuário configura a sessão, e já passa ela com a autenticação. Não precisamos mudar quase nada no código, e nem nos preocupar com tudo o que a AWS fornece.

```python
from aiobotocore.session import get_session

session = get_session(autenticação)

routes = [
    SQSRoute("my_queue", session),
]

manager = Manager(routes=routes)
manager.run()
```

## Recebendo o cliente
Essa é um pouco mais complicada, mas mais performática. Hoje, cada interação com o SQS instancia um cliente, interage com o SQS e finaliza esse cliente. Algo assim:
```python
async with session.create_client("sqs") as client:
    client.delete_message(...)
```

Isso funciona, mas traz algum desperdício de desempenho. A desvantagem é que não daria mais para usar o `Manager`, já que já tenho que estar em código `async` para instanciar o cliente:

```python
from aiobotocore.session import get_session

session = get_session()

async def run():
        async with session.create_client(autenticação) as client:
            routes = [
                SQSRoute("my_queue", client)
            ]
            
            dispatcher = Dispatcher(routes=routes)
            await dispatcher.dispatch_providers()

asyncio.run(run())
```

Bem mais complicado, mas mais performático.
